# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AccentureAssessment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AccentureAssessment
pod 'Alamofire'
pod 'RealmSwift'
pod 'RxSwift', '~> 6.6'
pod 'RxCocoa', '~> 6.6'

  target 'AccentureAssessmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AccentureAssessmentUITests' do
    # Pods for testing
  end

end
